<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>advice rule</name>
  <uuid>4cd0961f-6e85-4390-af10-52e33934dbc5</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Name is defined
then
    set decision to `Hello { Name }!`; ]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
